### ISSUE TITLE
How to use with a UI-library like bootstrap-vue?

### ISSUE THREAD

**Issue by pimlie** [nuxt/components#11]
**Describe the bug**
Also see discussion on discord.

bootstrap-vue has multiple ways to import components:
```js
import { BAlert } from 'bootstrap-vue'
import { BAlert } from 'bootstrap-vue/esm/index.js'
import { BAlert } from 'bootstrap-vue/esm/components/alert/index.js'
import { BAlert } from 'bootstrap-vue/esm/components/alert/alert.js'
import { BAlert } from 'bootstrap-vue/src/components/alert/alert.js'
```
But I am unable to get any of them to work atm as the following error is logged (that path is the correct path). I also tried to manually add a default export but that didnt work either.

```
These dependencies were not found:
* node_modules/bootstrap-vue/esm/components/alert/alert.js in ./src/layouts/default.vue
...
```

**To Reproduce**
- add bootstrap-vue to a project
- add a `<b-alert show>Alert!</b-alert>` somewhere in a component
- configure nuxt/components somehow to use bootstrap-vue

**Expected behavior**

I was expecting that I could use nuxt/components to also load components from ui-libraries like bootstrap-vue

**Screenshots**

**Additional context**

**Comment by pi0** [comment]
We have bunch of options for dirs and and `components:hook` useful for library authors (https://github.com/nuxt/components#library-authors). However it might be so tricky to integrate complex libraries like bootstrap-vue since it also registers directives and have component plugin dependencies (component groups)
