### ISSUE TITLE
support auto generated components dir

### ISSUE THREAD

**Issue by danielroe** [nuxt/components#111]
I'd like to be able to template components within a folder in the build directory (by a module), and register this folder with `@nuxt/components`.

At the moment, doing this gives the following error: `Components directory not found`. This error can be suppressed by setting `{ watch: true }` but then the components are never loaded.

See https://github.com/nuxt-community/sanity-module/issues/51 for context.

**Comment by pi0** [comment]
I think a better approach would be using a plugin to inject generated context and using them from components. This would allow directly adding components directory within module to `components` config and avoid generating templates.

**Comment by Fyroman** [comment]
So, I'm guessing this can't be done? I see you are adding templates and plugins in this module and you can't really circle back to it.

**Comment by pi0** [comment]
@Fyroman actually it is possible using async `components:dir` hook to make components module waiting that directory is created (in this case second module should generate dir itself instead of using `addTemplate` since it is a deferred function) 

Yet i would highly recommend not using templated components but instead injecting service with a sperate plugin that injects `$myLib` for usage inside component.
