### ISSUE TITLE
components w/ Array definition

### ISSUE THREAD

**Issue by mcdmaster** [nuxt/components#195]
**Is your feature request related to a problem? Please describe.**

In `@nuxt/components`, although I am appreciating that we can configure `components`, listing file path entries using `Array` like below, I always face a set of errors (described later) when compiling a `nuxt` app:
```
components: [
  {
    path: './components/',
    extensions: ['vue'],
  },
  'AppLink',
  'SideMenu',
  'DetailCard',
],
```

**Describe the solution you'd like**

The errors like below were eliminated:
```
 ERROR  [Vue warn]: Invalid value for option "components": expected an Object, but got Array.                 18:19:20  
 ERROR  [Vue warn]: Invalid component name: "0". Component names should conform to valid custom element name in html5 specification.
```

**Describe alternatives you've considered**

Tuning `eslint` configuration or something else which may soup up my development activities

**Additional context**

Apologies if similar issue can be found as previously resolved, but I wanted to see its reference, Thank you in advance

**Comment by NozomuIkuta** [comment]
@mcdmaster 

It seems that Vue warns you rather than Nuxt or Nuxt Components.

You set up `components` options as expected by Nuxt Components' type definition:

https://github.com/nuxt/components/blob/74b343db4f4fcd802851d5f951d8c654a3cf8f61/src/types.ts#L37-L46

```javascript
import { NuxtConfig } from '@nuxt/types'

const config: NuxtConfig = {
  components: [
    {
      path: './components/',
      extensions: ['vue'],
    },
    'AppLink',
    'SideMenu',
    'DetailCard',
],
```

Actually, since you are using `nuxt.config.ts`, if you violates type definition, Nuxt even can't build the app because TypeScript compilation fails.

<img width="1320" alt="Screenshot of intentional type violation" src="https://user-images.githubusercontent.com/16436160/118827492-62dcc300-b8f7-11eb-90e3-519b4363809a.png">

---

Since there is no steps to reproduce provided, I can't be 100% sure, but  I guess the error message you see is about the `components` of Vue's constructor options. You might want to check if it's set up as an array somewhere.

```javascript
// Some.vue
export default {
  components: [
    { /* Definition */ } // => Key is 0 and Vue will use is as the name of the component
  ]
}
```

**Comment by NozomuIkuta** [comment]
@mcdmaster 

If your issue is resolved, it would be appreciated if you close it.
Unfortunately, I can't close issues in this repository, but only author of the issue and the Nuxt team can.

**Comment by mcdmaster** [comment]
@NozomuIkuta 

Thank you for heads-up. Yes, I think we can close this issue for now.
Indeed, I am trying to implement "bracketed" components definition like below.
My understanding is that this may be one of applicable cases.

```
const config: NuxtConfig = {
  components: [
    {
      path: './components/',
      extensions: ['vue'],
    },
    {
      path: './node_modules/vue-spinner/src/',
      pattern: 'ScaleLoader.vue',
    },
],
```
