### ISSUE TITLE
Use image in Library Authors

### ISSUE THREAD

**Issue by leandromatos-hotmart** [nuxt/components#45]
I am creating an external component library to use with Nuxt. What I need is to use an image inside my component, and that image lives in the component library.

Assuming I have the following directory organization, how do I get this image to appear in the Nuxt project that consumes the component library? It is possible?
```
| node_modules/
---| my-library/
------| assets
---------| some-image.png
------| components/
---------| SomeComponent.vue // My image is used here
------| nuxt.js
| pages/
---| index.vue
| nuxt.config.js
```

**Comment by leandromatos-hotmart** [comment]
If i use an image with relative path, it's work on both sides, Nuxt App and Components Library.

SomeComponent.vue
```vue
<template>
  <img src="../assets/some-image.png" />
</template>
```

If i use an image with relative path, its works on both sides, Nuxt App and Components Library.

Is there a way to use an asset directory alias in my Component Library that will also work with Nuxt?

**Comment by pi0** [comment]
Hi @leandromatos-hotmart. You can use something like `this.options.alias['~my-lib'] == __dirname` inside your nuxt module to define alias :) But I would suggest sticking with relative paths unless it is going to complex because relying on an alias would be addictive! (any usage of your component library like bundling, testing, making general vue library needs this alias)
