### ISSUE TITLE
No warnings / errors if you use a nonexistent component - is this intended?

### ISSUE THREAD

**Issue by earslap** [nuxt/components#59]
I found this project through the release notes of nuxt; if this is the wrong place to ask this question please let me know.

**Describe the bug**
I was surprised by the following behavior: If you use a component with a random name in your template... nuxt dev server builds everything merrily without any complaints and shows you a preview with the component missing. I'd expect some sort of import failure at some point - is this intended behavior?

**To Reproduce**
1. Create a new project through create-nuxt-app
2. Delete Logo.vue (or rename `<Logo />` in index page to something random

**Expected behavior**
I expected to see a build error. At least a warning in case it is a typo.

**Comment by pi0** [comment]
Hi @earslap unfortunately yes since vue can only find-out about this in runtime and we can't do much about this since loader is optional.

The issue is hopefully mitigated in components v2 (with nuxt 2.15+) since if loader fails, plugin fallback helps. We will continue to to mitigate such DX issues by integrating better with ide plugins like vetur and a UI to browse list of discovered components (currently a readme is auto generated)
